---
- name: Install keepalived
  hosts: vnc_proxies
  become: yes

  tasks:
    - name: Install keepalived package
      apt:
        name: keepalived
        state: present
        update_cache: yes
