---
- name: Install keepalived
  hosts: vnc_proxies
  become: yes

  tasks:
    - name: Install keepalived package
      apt:
        name: keepalived
        state: present
        update_cache: yes
    - name: Create directory for check scripts
      file:
        path: /etc/keepalived/scripts
        state: directory
        mode: "0755"

    - name: Copy the check_haproxy script
      copy:
        content: |
          #!/bin/sh
          systemctl is-active --quiet haproxy
        dest: /etc/keepalived/scripts/check_haproxy.sh
        owner: root
        group: root
        mode: "0755"

    - name: Copy the correct keepalived config for each host
      copy:
        src: "keepalived/{{ inventory_hostname }}.conf"
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart keepalived

  handlers:
    - name: Restart keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
